/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NartyRouteImport } from './routes/narty'
import { Route as OklejaniePpfRouteImport } from './routes/oklejanie-ppf'
import { Route as RoweryRouteImport } from './routes/rowery'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NartyRoute = NartyRouteImport.update({
  id: '/narty',
  path: '/narty',
  getParentRoute: () => rootRouteImport,
} as any)
const OklejaniePpfRoute = OklejaniePpfRouteImport.update({
  id: '/oklejanie-ppf',
  path: '/oklejanie-ppf',
  getParentRoute: () => rootRouteImport,
} as any)
const RoweryRoute = RoweryRouteImport.update({
  id: '/rowery',
  path: '/rowery',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/narty': typeof NartyRoute
  '/oklejanie-ppf': typeof OklejaniePpfRoute
  '/rowery': typeof RoweryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/narty': typeof NartyRoute
  '/oklejanie-ppf': typeof OklejaniePpfRoute
  '/rowery': typeof RoweryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/narty': typeof NartyRoute
  '/oklejanie-ppf': typeof OklejaniePpfRoute
  '/rowery': typeof RoweryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/narty' | '/oklejanie-ppf' | '/rowery'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/narty' | '/oklejanie-ppf' | '/rowery'
  id: '__root__' | '/' | '/narty' | '/oklejanie-ppf' | '/rowery'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NartyRoute: typeof NartyRoute
  OklejaniePpfRoute: typeof OklejaniePpfRoute
  RoweryRoute: typeof RoweryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/narty': {
      id: '/narty'
      path: '/narty'
      fullPath: '/narty'
      preLoaderRoute: typeof NartyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oklejanie-ppf': {
      id: '/oklejanie-ppf'
      path: '/oklejanie-ppf'
      fullPath: '/oklejanie-ppf'
      preLoaderRoute: typeof OklejaniePpfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rowery': {
      id: '/rowery'
      path: '/rowery'
      fullPath: '/rowery'
      preLoaderRoute: typeof RoweryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NartyRoute: NartyRoute,
  OklejaniePpfRoute: OklejaniePpfRoute,
  RoweryRoute: RoweryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
